import { type NextPage } from "next";
import Head from "next/head";
import { Header } from "~/components/header";
import { Login } from "~/components/login";
import { Footer } from "~/components/footer";

const Home: NextPage = () => {
  // TODO: if logged in then redirect to IV list page

  return (
    <>
      <Head>
        <title>POGO IV Calculator</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <main className="flex h-screen items-center justify-center">
        <div className="flex w-screen justify-center">
          <Login></Login>
        </div>
      </main>
      <footer className="bg-primary">
        <Footer></Footer>
      </footer>
    </>
  );
};

export default Home;
