import { type NextPage } from "next";
import { useRouter } from "next/router";
import Head from "next/head";
import { Header } from "~/components/header";
import { Footer } from "~/components/footer";

const IVList: NextPage = () => {
  const router = useRouter();
  const { ivId } = router.query;
  return (
    <>
      <Head>
        <title>POGO IV Calculator</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <main className="flex h-screen justify-center">
        <div className="flex w-screen">
          <p>IV list id: {ivId}</p>
        </div>
      </main>
      <footer className="bg-primary">
        <Footer></Footer>
      </footer>
    </>
  );
};

export default IVList;
